# Generated by Django 4.0 on 2022-04-11 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryClothes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('manufacturerDate', models.DateField()),
                ('material', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('sizeCountry', models.CharField(max_length=255)),
                ('washingType', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('weight', models.FloatField(null=True)),
                ('fitType', models.CharField(max_length=255)),
                ('closureType', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=255)),
                ('countryOrigin', models.CharField(max_length=255)),
                ('CategoryClothes', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clothes.categoryclothes')),
            ],
        ),
        migrations.CreateModel(
            name='ItemClothes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(null=True)),
                ('discount', models.FloatField(null=True)),
                ('promoText', models.CharField(max_length=255)),
                ('decription', models.CharField(max_length=255)),
                ('inventory', models.CharField(max_length=255)),
                ('isForSale', models.BooleanField(default=True)),
                ('Clothes', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes')),
            ],
        ),
    ]
