# Generated by Django 4.0 on 2022-04-08 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('language', models.CharField(max_length=255)),
                ('dimesions', models.CharField(max_length=255)),
                ('edition', models.CharField(max_length=255)),
                ('CategoryBookID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.categorybook')),
                ('PublisherID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.publisher')),
            ],
        ),
    ]
