# Generated by Django 4.0 on 2022-04-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_num_of_pages_book_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='CategoryBookID',
            new_name='CategoryBook',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='PublisherID',
            new_name='Publisher',
        ),
    ]
