# Generated by Django 4.0 on 2022-04-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_imagebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebook',
            name='src',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
