# Generated by Django 4.0 on 2022-04-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_imagebook_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Img',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.imagebook'),
        ),
        migrations.AlterField(
            model_name='imagebook',
            name='src',
            field=models.ImageField(upload_to=''),
        ),
    ]
