# Generated by Django 4.0 on 2022-04-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_img_alter_imagebook_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Img',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.imagebook'),
        ),
    ]
