# Generated by Django 4.0.3 on 2022-04-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryShoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImageShoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.FloatField(null=True)),
                ('sizeCountry', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('weight', models.FloatField(null=True)),
                ('manufactureDate', models.DateField(null=True)),
                ('countryOrigin', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('upperMaterial', models.CharField(max_length=255)),
                ('sideMaterial', models.CharField(max_length=255)),
                ('liningMaterial', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=255)),
                ('CategoryShoes', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoes.categoryshoes')),
            ],
        ),
        migrations.CreateModel(
            name='ItemShoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(null=True)),
                ('discount', models.FloatField(null=True)),
                ('promo_text', models.CharField(max_length=255)),
                ('decription', models.CharField(max_length=255)),
                ('inventory', models.CharField(max_length=255)),
                ('is_for_sale', models.BooleanField(default=True)),
                ('Shoes', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoes.shoes')),
            ],
        ),
    ]
